sudo: false
language: python

python:
  - "3.6"

env:
  - DJANGO="django==1.11.7"

install:
  - pip install $DJANGO
  - pip install django-ipware
  - pip install -e .
  - pip install coverage
  - pip install coveralls

script: coverage run --source=trapdoor tests/runtests.py

after_success:
  coveralls
